name: Trigger auto deployment for aca-dn8-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/aca-dn8-api-AutoDeployTrigger-24bafd67-7d61-4852-a657-9d53a7edc471.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACADN8API_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACADN8API_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACADN8API_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.ACADN8API_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACADN8API_REGISTRY_PASSWORD }}
          containerAppName: aca-dn8-api
          resourceGroup: Default
          imageToBuild: ghcr.io/aca-dn8-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


